name: Archive Artifacts

on:
  # Trigger on a schedule and/or manually.
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Web Archiver Composite Action
        uses: annabarnes1138/web-archiver-action@main
        with:
          artifacts: |-
            [
              { "url": "https://hrt.coffee", "description": "List of hormone suppliers" }
            ]
          schedule: "Weekly on Fridays at midnight (UTC)"
          static_description: "diyhrt.info, diyhrt.market, hrt.coffee, hrtcafe.net, transfemscience.org genderdysphoria.fyi and a few others in case something goes wrong."
          github_token: ${{ secrets.GITHUB_TOKEN }}
